name: Check grammer

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.md'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Ltex
        run: |
          wget "https://github.com/valentjn/ltex-ls/releases/download/16.0.0/ltex-ls-16.0.0-linux-x64.tar.gz"
      
      - name: Install Ltex
        run: |
          tar -xf ltex-ls-16.0.0-linux-x64.tar.gz
          ltex=$(pwd)/ltex-ls-16.0.0/bin/ltex-cli

      - name: Prepare enviorment
        run: shopt -s globstar
      
      - name: Check files
        run: $ltex **/*.md --verbose
          
