name: Check grammer

on:
  push:
    paths:
      - '**/*.md'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find changes
        id: modified
        run: |
          GITHUB_OUTPUT="files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})"

      - name: List changes
        run: |
          echo ${{ steps.modified.outputs.files }}

      - name: Compare to empty
        if: steps.modified.outputs.files == ''
        run: exit 1

      - name: Download Ltex
        if: steps.modified.outputs.files != ''
        run: |
          wget "https://github.com/valentjn/ltex-ls/releases/download/16.0.0/ltex-ls-16.0.0-linux-x64.tar.gz"
      
      - name: Install Ltex
        if: steps.modified.outputs.files != ''
        run: |
          tar -xf ltex-ls-16.0.0-linux-x64.tar.gz
      
      - name: Check files
        if: steps.modified.outputs.files != ''
        env:
          FILES: ${{ steps.modified.outpus.files }}
        run: $PWD/ltex-ls-16.0.0/bin/ltex-cli --verbose $FILES
          
