name: Convert Markdown to DOCX

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert Markdown to DOCX
        run: |
          # Convert all .md files to .docx
          for file in $(find . -name '*.md'); do
            docx_file="${file%.md}.docx"
            pandoc "$file" -o "$docx_file"
          done

      - name: Remove orphaned DOCX files
        run: |
          # Find all .docx files and check if the corresponding .md file exists
          for docx_file in $(find . -name '*.docx'); do
            md_file="${docx_file%.docx}.md"
            if [ ! -f "$md_file" ]; then
              echo "Removing orphaned DOCX: $docx_file"
              rm "$docx_file"
            fi
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.email "aligator.h0spital.e@gmail.com"
          git config --global user.name "GitHub Actions"
          git add **/*.docx
          git commit -m "Auto-converted markdown files to docx and cleaned up orphaned docx files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}