name: Convert Markdown to DOCX

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert all to md
        run: ./script.sh

      - name: Commit and Push converted files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Convert .md files to .docx on push"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
